FROM golang:1.16 as builder

ENV GO111MODULE=on

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY .env .

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/app

FROM scratch

COPY --from=builder /go/bin/app /go/bin/app

EXPOSE 8080

ENTRYPOINT ["/go/bin/app"]